name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: |
          mkdir -p bin/
          make install
          make gen
          go test -v ./...
      - name: Dry build
        run: |
          go build -o ./tmp/main ./cmd/web/main.go




